### ISSUE TITLE
Precourse/Lesson3-JS-II/README.md incorrect statement

### ISSUE THREAD

**Issue by mjd02** [LambdaSchool/Precourse#540]
**.push adds an item to the end of the array, incrementing it's length by 1. (.push returns the entire array)**

However, .push returns the length of the new array.

**Comment by demol6798** [comment]
.push edits the original array. so after pushing on one line you return on the second.

**Comment by etisdew** [comment]
I'm on it. You are correct sir.

**Comment by etisdew** [comment]
Should address issue #540 could you close if pr satisfys you?
