### ISSUE TITLE
Typo # switch . 

### ISSUE THREAD

**Issue by cesarnml** [LambdaSchool/Precourse#620]
`querySelector (and querySelectorAll) is a new method that takes a CSS style selector as it's argument. Remember that we can ask for classes in CSS using the #, ids using the ., and elements by using the element name (eg: 'body'). These selectors will use the same format. It is best to only use ids with querySelector because it will only return the first item matching that selector.`

Aren't classes referenced with the . and ids with the #?

**Comment by etisdew** [comment]
It is reading correctly for me, would you beable to make the amendment or point out the line and file this occurs?

**Comment by etisdew** [comment]
I can confirm the offending text is not there at this moment and reads correctly if you'd be so kind as to close this.
