### ISSUE TITLE
Lesson 6 CSS File

### ISSUE THREAD

**Issue by technoeunuch** [LambdaSchool/Precourse#629]
It is not explicitly stated in the homework that the newly created 'styles.css' file must be linked to 'homework.html' file. The instruction is only to uncomment the styles tags. Is it supposed to be implied?

**Comment by etisdew** [comment]
It is implied that the main readme describes the link tag, I personally found it difficult managing multiple readmes aswell as windows when I first started. This should be consolidated or emphasis should be placed on keeping readme resources in one location..
