### ISSUE TITLE
Lesson2 Typos and Ambiguity in homework-readme.txt

### ISSUE THREAD

**Issue by izulien** [LambdaSchool/Precourse#766]
On line 20 "google" **_could_** read "Google" though this is just a bit picky, I figured I'd add it since there were already edits to the file needed.
> an img tag in each list item linking to your favorite food. (Use **google** image search to find a photo, if you can't 

On line 24 "you" should be "your"
> A. Add style tags to **you** HTML document.

On line 27 "seond" should read "second"
> D. Give the span in your **seond** div the id "spanId".

On line 48 "recoomend" should read "recommend"
> do some further homework, I **recoomend** the additional resources in the README or https://www.w3schools.com/css/default.asp)

There is some minor ambiguity in section III.  The heading suggests we are to create our style file and link it to our HTML though the first bullet / instructions tells us to FIND a file and no instruction suggests we link the file.

> III. Create an external style sheet and import all of our previous style rules into the new stylesheet.
>   A. Find styles.css file in this folder.
>   B. COPY all of your style rules to this new file. (Do not include the style tags!)
>   C. Place: `<!--` in front of your first style tag.
>   D. Place: `-->` after your closing style tag.

**Suggested Change**

III. Create an external style sheet and import all of our previous style rules into the new stylesheet.
  A. Create a new file named styles.css this folder. (Bonus points if you use GIT commands!)
  B. COPY all of your style rules to this new file. (Do not include the style tags!)
  C. Place: `<!--` in front of your first style tag.
  D. Place: `-->` after your closing style tag.
  E. Add a link to your new stylesheet.

**Comment by SunJieMing** [comment]
Thanks for the feedback!  The instructions have been updated.
