### ISSUE TITLE
Lesson 2 has wrong height for thirdDiv to fit in images

### ISSUE THREAD

**Issue by MarioJr92** [LambdaSchool/Precourse#782]
In the homework-readme.txt for part II. Add some style letter G. Add a style rule to 'thirdDiv' changing the height to 600px and the width to 500px. The images overlaps the height of the box, I changed the height to 800px so the images are perfectly positioned inside of the box.

**Comment by izulien** [comment]
@MarioJr92 I don't see where image height is ever mentioned in the instructions.

It is slightly implied to have a 400x200 image (based on I. 3's lorempixel link)

**Comment by MarioJr92** [comment]
@izulien Image height isn't mentioned. I'm talking about the height of the thirdDiv. If I leave the height of the thirdDiv to 600px the images with the width of 400px overlaps it. So I changed the height of the thirdDiv so the images can fit in.
<img width="634" alt="screen shot 2018-02-08 at 3 35 09 pm" src="https://user-images.githubusercontent.com/31669582/35996871-b619f8e2-0ce5-11e8-853d-f3a0f7ae3e0f.png">

**Comment by izulien** [comment]
@MarioJr92 Certainly, if we set a height and width on the div, suggesting a height and width on the image is likely a smart plan.

**Comment by adsingh14** [comment]
1. According to lorempixel link, image height/width should be of 200/400(in px).
2. If we want to ignore the `step (1)`, then we have to set min-height ~height~ of `#thirdDiv` to 600px. 

_You can also check my repo where I followed step (1)._
