### ISSUE TITLE
Typing error 

### ISSUE THREAD

**Issue by Ksantacr** [LambdaSchool/Precourse#853]
In Lesson3-CSS-Positioning [README.md](https://github.com/LambdaSchool/Precourse/blob/master/Lesson3-CSS-Positioning/README.md#justify-content-and-align-items) file has a typing error in second line:

> We can use the **justify-contet** and align-items properties ...

It's **justify-content**

**Comment by SunJieMing** [comment]
Thanks!  Fixed
